AttendanceGpi.Web/Controllers/EmployeeAccountController.cs
using AttendanceGpi.Web._Repository;
using AttendanceGpi.Web.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AttendanceGpi.Web.Controllers
{
    [Authorize(Roles = "Employee")]
    public class EmployeeAccountController : Controller
    {
        private IEmployee _repo;

        public EmployeeAccountController(IEmployee repo)
        {
            _repo = repo;
        }

        //
        // GET: EmployeeAccount
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            return View();
        }

        //
        // GET: EmployeeAccount/Info
        public ActionResult Edit()
        {
            var userId = User.Identity.GetUserId();
            return View(_repo.Find(userId));
        }

        //
        // POST: EmployeeAccount/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id, UserName, Picture, Name, Position, SchedId")] EmployeeEditViewModel employee)
        {
            if (ModelState.IsValid)
            {
                var originalPicture = employee.Picture;
                HttpPostedFileBase file = Request.Files["Picture"];
                employee.Picture = (file.ContentLength > 0)
                    ? UploadPicture(file)
                    : originalPicture;

                _repo.Edit(employee);
                TempData["Success"] = "You have successfullly updated your information.";
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        #region Helper
        private string _myRandomNumber;
        private static readonly Random Random = new Random();
        private static readonly object SyncLock = new object();

        //Upload picture and send to Files folder.
        public string UploadPicture(HttpPostedFileBase pictureFile)
        {
            _myRandomNumber = RandomNumber(0, 10000000).ToString("D");
            int newPictureId = Int32.Parse(_myRandomNumber);
            string newPictureName = newPictureId + ".png";
            string baseDirectory = Server.MapPath("~/Images/");

            pictureFile.SaveAs((baseDirectory + (newPictureId + ".png")));
            return newPictureName;
        }

        private static int RandomNumber(int min, int max)
        {
            lock (SyncLock)
            {
                return Random.Next(min, max);
            }
        }
        #endregion
    }
}

AttendanceGpi.Web/Controllers/ScheduleController.cs
using AttendanceGpi.Core;
using AttendanceGpi.Web._Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AttendanceGpi.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ScheduleController : Controller
    {
        private ISchedule _repo;

        public ScheduleController(ISchedule repo)
        {
            _repo = repo;
        }

        //
        // GET: Schedule
        public ActionResult Index()
        {
            return View(_repo.Show());
        }

        //
        // GET: Schedule/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: Schedule/Create/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SchedName, SchedStart, SchedEnd")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                _repo.Create(schedule);
                TempData["Success"] = "You have successfully created " + schedule.SchedName;
                return RedirectToAction("Index");
            }

            return View(schedule);
        }

        //
        // GET: Schedule/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_repo.Find(id));
        }

        //
        // POST: Schedule/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "SchedId, SchedName, SchedStart, SchedEnd")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                _repo.Edit(schedule);
                TempData["Success"] = "You have successfullly updated " + schedule.SchedName;
                return RedirectToAction("Index");
            }
            return View();
        }



    }
}

AttendanceGpi.Web/Views/Shared/LogInfo.cshtml
@model AttendanceGpi.Web.ViewModel.LogViewModel
<div class="col-sm-6 body-2-container">
    <div class="body-2">
        <div class="col-xs-6">
            <img src="/Images/@Model.Picture" alt="" class="img-user img-style">
        </div>
        <div class="col-xs-5 user-details">
            <label>Name</label><br>
            <p>@Model.Name &nbsp;</p>
            <label>Position</label><br>
            <p>@Model.Position &nbsp;</p>
            <label>Shift</label><br>
            <p>@Model.Shift &nbsp;</p>
            <label for="">@Model.TimeLabel</label>
            <p class="@Model.TimeTextStyle">@Model.Time</p>
        </div>
    </div>
</div>

AttendanceGpi.Web/Views/Shared/ReportResult.cshtml
@model IEnumerable<AttendanceGpi.Web.ViewModel.AdminLogViewModel>


<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.SchedName)</th>
            <th>@Html.DisplayNameFor(m => m.TimeIn)</th>
            <th>@Html.DisplayNameFor(m => m.TimeOut)</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@item.SchedName</td>
                <td><p class="@item.TimeInStyle">@item.TimeIn</p></td>
                <td><p class="@item.TimeOutStyle">@item.TimeOut</p></td>
            </tr>
        }
    </tbody>
</table>

AttendanceGpi.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body onload="startTime()" id="overlay">
    @switch (@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString())
    {
        case "Home":
        case "Account":
            @RenderBody()
            break;

        default:
            @Html.Partial("_Navigation");
            <div class="main">
                <div class="container sub-title-container">
                    @RenderBody()
                </div>
            </div>
            break;
    }

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/scripts")
    <script>
        $(function () {
            var success = "@(TempData["Success"] as string)";
            var error = "@(TempData["Error"] as string)";

            if (success !== "") {
                toastr.success(success);
            }

            if (error !== "") {
                toastr.error(error);
            }
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

AttendanceGpi.Web/Views/Shared/_Navigation.cshtml
@using Microsoft.AspNet.Identity
@using AttendanceGpi.Web._Consolidator
<nav class="navbar  navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="
                   @if (User.IsInRole("Admin"))
                   {
                       @: /Admin
                   }
                   else
                   {
                       @: /EmployeeAccount
                   }
                   ">Logo</a>

        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            @if (User.IsInRole("Admin"))
            {
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Employees", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Schedules", "Index", "Schedule")</li>
                    <li>@Html.ActionLink("Reports", "Index", "Report")</li>
                </ul>
            }
            else
            {
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Update Information", "Edit", "EmployeeAccount")</li>
                </ul>
            }

            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
            {
                @Html.AntiForgeryToken()
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                    </li>
                

                    <li>
                        <a href="javascript:document.getElementById('logoutForm').submit()"><span class="glyphicon glyphicon-log-in"></span> Log off</a>
                    </li>
                </ul>
            }

        </div>
    </div>
</nav>